# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9629b3a81c5edf7781a31e2677163827a9f4636da2d7cff96174ec1f5889993d18c138b767ead9f8af77c260bf2aeb64215ac604120518d87bbc850ea1563f7d

test:
  secret_key_base: a5e90959d603ffe439fb54b174bd0cd56801fbf80a112cc9b236225c5b5b9a2cee8726cbf93d7ae1472cac956111465d33277efe5c42625a1b1cef4c76e0d371

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
